= Softwareentwicklung im Team: Korrektorinnenbewerbung
WS19/20
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Problemstatement

Aktuell bewerben sich engagierte Studenten über ein Umfrageformular im Ilias auf offene Korrektoren- und Tutorenstellen.
Dieses Formular hat durchaus Vorteile, die wir in unserem System übernehmen werden, wie beispielsweise die Abgrenzung der persönlichen Daten
des Bewerbers von den Bewerbungen der einzelnen Module und das Umgehen von einzelnen Formularen/Umfragen pro Bewerbung für ein Modul.

Allerdings lässt die Geschwindigkeit des Backend Vorgangs zu wünschen übrig und das Weiterleiten bzw. Kopieren einer Bewerbung nimmt mehr
Zeit in Anspruch als es sollte. Auch erfahren Studenten erst sehr spät etwas über den Status ihrer Bewerbung, was ein gut geplantes Semester schwer macht.
Die Modularität ist nicht gegeben, da eine einmal abgeschickte Bewerbung nicht ändern kann.

== Systembeschreibung

In jedem Semester werden studentische Hilfskräfte für den Übungsbetrieb benötigt. In (zumindest) den Grundlagenveranstaltungen wird dazu ein gemeinsames Bewerbungsverfahren benutzt:

* Bewerber füllen einen Fragebogen aus.
* Nach Ablauf der Frist werden die Bewerberinnen, die potentiell für eine Stelle in Frage kommen gruppiert und den Verantwortlichen der Veranstaltung zur Verfügung gestellt. Bewerberinnen kommen in Frage, wenn sie eine Veranstaltung nicht ausgeschlossen haben.
* Die Verantwortlichen geben für jede Bewerbung eine Priorität an.
* Die Verteilung auf die einzelnen Veranstaltungen werden von einer verantwortlichen Person manuell durchgeführt, dazu wird aber eine hinreichend gute Darstellung der gesammelten Informationen gebraucht
* Am Ende sollen automatisch die Einstellungsbögen für die Personalabteilung als PDF erzeugt werden

== Zentrale Ziele

* *Effizienz*:
  Bewerber und Organisator erhalten schnelle Rückmeldung und einzelne Bewertungsschritte gehen flüssiger ineinander über
* *Benutzbarkeit*:
  Übersichtliche UI's mit intuitiven Buttons zum Hinzufügen von Bewerbungen direkt vom Dashboard
* *Zuverlässigkeit*:
   Wenig Platz für Fehlermöglichkeiten und viele Tests in der Entwicklungsphase

== Features

* Organisiertes, übersichtliches Dashboard mit Statusanzeige der Bewerbungen
* Eigene Exceptions mit konkreten Fehlerhinweisen
* Überarbeitungsmöglichkeit der einzelnen Bewerbungen bis zum Bewerbungsschluss
* Organisatoren und Verteiler können Priorität/Zuteilung ändern bevor Einstellungsbögen erstellt werden