name: Checkstyle

on:
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron:  '0 11,12,13,14,15,16,17 * * 1,2,3,4,5'

jobs:
  Checkstyle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkstyleMain